services:
  node_01:
    image: "minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1"
    hostname: minio_01
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-server_admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_SECRET:-CHANGEm3!}
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address 0.0.0.0:9001
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
      placement:
        constraints:
          - node.hostname == ${VM_MINIO_NAME}

      labels:
        - traefik.enable=true
        - traefik.http.routers.minio.entrypoints=https
        - traefik.http.routers.minio.rule=Host(`s3.${TLD?TLD not set}`)   
        - traefik.http.routers.minio.tls=true
        - traefik.http.routers.minio.tls.certresolver=le
        - traefik.http.routers.minio.service=minio
        - traefik.http.services.minio.loadbalancer.server.port=9000
  
        - traefik.http.routers.minio_admin.entrypoints=https
        - traefik.http.routers.minio_admin.rule=Host(`minio.${TLD?TLD not set}`)
        - traefik.http.routers.minio_admin.tls=true
        - traefik.http.routers.minio_admin.tls.certresolver=le
        - traefik.http.routers.minio_admin.service=minio_admin
        - traefik.http.services.minio_admin.loadbalancer.server.port=9001
    volumes:
      - ${MINIO_DATA}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.rule=Host(`s3.${TLD?TLD not set}`)   
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=le
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
 
      - traefik.http.routers.minio_admin.entrypoints=https
      - traefik.http.routers.minio_admin.rule=Host(`minio.${TLD?TLD not set}`)
      - traefik.http.routers.minio_admin.tls=true
      - traefik.http.routers.minio_admin.tls.certresolver=le
      - traefik.http.routers.minio_admin.service=minio_admin
      - traefik.http.services.minio_admin.loadbalancer.server.port=9001
    networks:
      - vnet_frontend
      - vnet_backend

networks:
  vnet_frontend:
    external: true
    name: vnet_frontend
  vnet_backend:
    external: true
    name: vnet_backend