macos:
        container_name: macos
        restart: 'always'
        image: sickcodes/docker-osx:naked
        labels:
            com.centurylinklabs.watchtower.enable: "false"
        ports:
            - 50922:10022
            - 5999:5999 # vnc
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /opt/macos/mac.qcow2:/image # Backed up on nas /Backup/home-assistant/
        networks:
            - macos_network
        environment:
            - DISPLAY=${DISPLAY:-:0.0}
            - GENERATE_SPECIFIC=true
            - DEVICE_MODEL=iMacPro1,1
            - SERIAL=SERIAL
            - BOARD_SERIAL=BOARD
            - UUID=UUID
            - MAC_ADDRESS=MAC
            - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=vncpass
            - TZ=America/Chicago
        devices:
            - /dev/kvm
        user: root