services:
  node:
    image: lissy93/dashy:latest
    hostname: dashy
    restart: always
    environment:
      NODE_ENV: production
      TZ: UTC
    expose:
      - 80
    ports:
      - 3773:80
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == ${VM_APP1_NAME?VM_APP1_NAME not set}
      labels:
        # traefik.enable is required because we don't expose all containers automatically
        - traefik.enable=true
        - traefik.http.routers.dashy.entrypoints=https
        - traefik.http.routers.dashy.rule=Host(`dashy.${TLD?TLD not set}`)
        - traefik.http.routers.dashy.tls=true
        - traefik.http.routers.dashy.tls.certresolver=le
        - traefik.http.services.dashy.loadbalancer.server.port=80
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - dashy-public:/app/public
    networks:
      vnet-frontend:
        ipv4_address: 172.19.0.50

networks:
  vnet-frontend:
    external: true

volumes:
  dashy-public: