services:
  node_01:
    image: hashicorp/vault
    hostname: vault-01
    restart: always
    environment:
      VAULT_ADDR: "http://${VM_MGMT_IP}:8200"
      VAULT_API_ADDR: "http://${VM_MGMT_IP}:8200"
      VAULT_LOCAL_CONFIG: |
          {
            "backend": {
              "consul": {
                "address": "consul-01:8500",
                "path": "vault/"
              }
            },
            "listener": [{
                "tcp": {
                  "address": "0.0.0.0:8200",
                  "tls_disable": true, 
                }
            }], 
            "default_lease_ttl": "168h", 
            "max_lease_ttl": "720h",
            "ui": true
          }
    expose:
      - 8200
    cap_add:
      - IPC_LOCK
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == vm-mgmt
      labels:
        # traefik.enable is required because we don't expose all containers automatically
        - traefik.enable=true
        - traefik.http.routers.vault.entrypoints=https
        - traefik.http.routers.vault.rule=Host(`vault.${TLD?TLD not set}`)
        - traefik.http.routers.vault.tls=true
        - traefik.http.routers.vault.tls.certresolver=le
        - traefik.http.services.vault.loadbalancer.server.port=8200
    command: server
    volumes:
      - vault-policies:/vault/policies
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    networks:
      vnet-frontend:
        ipv4_address: 172.19.0.4

networks:
  vnet-frontend:
    external: true
    name: vnet-frontend

volumes:
  vault-data:
  vault-policies:
  vault-logs: